### PR TITLE
Improved reporting of multiple expectation fails and passes for Jasmine.

### PR DESCRIPTION
**Pull request by GCHQDeveloper911**
Submitted as part of https://github.com/webdriverio/webdriverio/issues/3125

### CODE REVIEW

**Comment by christian-bromann** [comment]
@GCHQDeveloper911 can you please sign the CLA. Also would you mind attaching a screenshot showing how this now looks like?

**Comment by GCHQDeveloper911** [comment]
Hi @christian-bromann, CLA now signed - but for completeness, could I ask you to make the same changes to the license file that you made in wdio-jasmine-framework to the license files in the other wdio repos? Many thanks!

**Comment by GCHQDeveloper911** [comment]
specreporter

**Comment by christian-bromann** [comment]
> could I ask you to make the same changes to the license file that you made in wdio-jasmine-framework to the license files in the other wdio repos?

sure

**Pull request merged**
